### ISSUE TITLE
Support for Risk of Rain 2: Seekers of the Storm

### ISSUE THREAD

**Issue by PollyThePancake** [tjosepo/ror2-editor#13]
New dlc is out, which added a bunch of new stuff to be unlocked. Would be great if someone could update it, might look into it myself tbh

**Comment by tjosepo** [comment]
It should be fairly easy to add by modifying the [challenges.tsx](https://github.com/tjosepo/ror2-editor/blob/main/src/challenges.tsx) file. 

The only thing we need is the title, description, achievement ID, unlock ID, and icon of the new achievements.

Looks like the wiki hasn't been updated yet, so I'm not sure where to find the IDs.

Feel free to open a pull-request if you have time 🙇‍♂️

**Comment by Gnomey123** [comment]
I just unlocked everything using this mod:
https://thunderstore.io/package/prodzpod/RealerCheatUnlocks/

I can give my config file for science

**Comment by tjosepo** [comment]
@Gnomey123 That would be very helpful. Using the IDs, we can find which achievement unlocks what.

**Comment by Gnomey123** [comment]
Here you go

[all-unlocked.zip](https://github.com/user-attachments/files/16776067/all-unlocked.zip)

**Comment by ekonruff** [comment]
reading these comments, how do i get seekers of the storm stuff. do i use that zip?

**Comment by Gnomey123** [comment]
Technically yes, you could just copy everything here into your file

**Comment by DaMrNelson** [comment]
My friends and I got frustrated of the bugged unlocks so I did did it myself. Long time enjoyer of this project. Thanks a ton for everything & I hope this helps others!

See PR: https://github.com/tjosepo/ror2-editor/pull/16

**Comment by PollyThePancake** [comment]
Great job! Tried finding the values myself but I didnt quite know where I was looking

**Comment by tjosepo** [comment]
The changes have been deployed! Seekers of the Storm is now supported by the editor!

A great thanks to everyone involved in this! 🎉
