### ISSUE TITLE
Make it support latest patch?

### ISSUE THREAD

**Issue by GlydetheSurfer** [tjosepo/ror2-editor#5]
Some items are still missing after i use it. the latest patch is april 19 version 1.2.3.1

**Comment by tjosepo** [comment]
Do you have a list of the missing items?

I'm aware about the Death Do Us part, challenge. Is there another one missing?

**Comment by GlydetheSurfer** [comment]
how do i get a list of them if they aren't unlocked?

**Comment by tjosepo** [comment]
Inside the game, you can go to into __Logbook > Challenges__ to see the list of challenges that haven't been unlocked.

To my knowledge, the only challenge the editor doesn't support is [Blocade Breaker](https://riskofrain2.fandom.com/wiki/Blockade_Breaker).

**Comment by GlydetheSurfer** [comment]
![image](https://user-images.githubusercontent.com/32045132/165886758-cd620112-90e1-45e6-8fdf-27be84c53423.png)

**Comment by tjosepo** [comment]
It's possible that the Unlock All feature is broken. It's also possible you did something wrong on your end. 🤔

I'd recommend you try the editor again, __with the game closed,__ and then check the challenges manually.

**Comment by GlydetheSurfer** [comment]
![image](https://user-images.githubusercontent.com/32045132/166087321-dbe1cb1f-c36c-41ee-9db3-e5b6d02451a0.png)
yah its just as you said, all the challenges are unlocked except blockade breaker. but.. what's this got to do with the items? i'm confused?

**Comment by tjosepo** [comment]
Great. You unlock items by doing the challenges. If every challenge is marked as completed, then you have every item unlocked.

Note that this save editor doesn't unlock DLC items. You actually need to buy the DLC to unlock them.

**Comment by GlydetheSurfer** [comment]
yes i have the dlc.. bought it a few days ago
